### ISSUE TITLE
decode without signKey

### ISSUE THREAD

**Issue by liuyao61** [renoguyon/vue-jwt#2]
Hi,

I'm wondering if there is a way to decode without setting the signKey as I don't think we don't need/shouldn't verify it on the client side?

**Comment by milewski** [comment]
definitely you shouldn't set the key available on the client side... anyone could inspect.. get the key... and generate tokens for themselves using the same key..  instead what you should do is:

```
JSON.parse(atob(token.split('.')[ 1 ]))
```

You dont need this library at all...

**Comment by renoguyon** [comment]
Hi @liuyao61 ,

You can update to version 1.1.0: signKey is now optional parameter. You can safely omit it if you just want to decode your token payload without verifying signature.

For information, JWT tokens can be generated using private/public key pairs. signKey parameter should only be used in that case: the client will only known the public key while server uses the private one to generate tokens.

If you're using a single signin key, well, you're better not to share that key with your client app :)
